### ISSUE TITLE
Is sequence matching exact?

### ISSUE THREAD

**Issue by svalkiers** [uio-bmi/compairr#29]
Hi,

I've been using CompAIRR for calculating the overlap between different repertoires. I noticed that, when computing the overlap between one sample and itself, CompAIRR produces a different (greater) number than the number of sequences present in that repertoire. For example, if repertoire _X_ would contain 200,000 clonotypes, the CompAIRR _n_x_n_ overlap matrix would return a number >200,000 for the overlap between _X_ and _X_. My question is therefore: is the CompAIRR result an approximation of the overlap between two repertoires or is it exact and am I misinterpretting the results?

For reference I used the following parameters:

`compairr -m -f -o output.tsv input.tsv`

Thank you.

Kind regards,
Sebastiaan Valkiers

**Comment by torognes** [comment]
By default (or with `-d 0`), the matching is exact. if you specify `-d 1` or `-d 2` or `-i`, also approximate matches will be included.

When you see numbers larger than 200 000 in the result for repertoire _X_ vs _X_, that should be because there are two or more identical sequences (with identical V- and J-genes) within repertoire X. If you had not used the `-f` option, it could also have been because the count of one or more of the sequences is larger than 1.

If you have 200 000 distinct sequences and the counts are all 1, then the resulting value should have been exactly 200 000.

**Comment by torognes** [comment]
Thanks for using CompAIRR! I hope you find it useful. Don't hesitate to ask more questions or suggest new features!

**Comment by svalkiers** [comment]
I have identified the issue (the product of duplicated sequences resulted in higher number of sequences than the size of the data sample).

In any case, thank you so much for the quick response. I really enjoyed using CompAIRR so far! Great tool for our community :)
