### ISSUE TITLE
Overlap metrics

### ISSUE THREAD

**Issue by svalkiers** [uio-bmi/compairr#30]
Hi,

Does CompAIRR allow the calculation of overlap metrics such as Jaccard or Morisita-Horn index or should this be done manually (afterwards)?

Thank you and kind regards,
Sebastiaan Valkiers

**Comment by torognes** [comment]
CompAIRR cannot directly compute metrics like Jaccard or Morisita-Horn index, so that has to be done afterwards.

It will only compute the sum of the products of the counts of all the matching sequences. Please see the overlap example in the README for details. Instead of the sum of the products of the counts, it can also compute the sum of the ratio, min, max, or mean, as indicated by the `-s` option. This may be helpful with some metrics.

**Comment by torognes** [comment]
We could consider adding this as a feature in the future.

**Comment by torognes** [comment]
Computation of the Morisita-Horn or Jaccard index have been added in version 1.7.0. Use the option `-s MH` or `-s Jaccard`, respectively.
